# Generated by Django 6.0 on 2025-12-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='value',
            new_name='price',
        ),
    ]
