# Generated by Django 6.0 on 2025-12-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='motor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
