# Generated by Django 6.0 on 2025-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
