# Generated by Django 6.0 on 2025-12-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='cars_total_value',
            new_name='cars_value',
        ),
    ]
